#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  2 02:54:40 2020

@author: jorge
"""

a=0
b=int(input())
c=int(input("Número para hacer secuencia de Fubonacci:")) 
if c<=0:
    print("Invalido")
elif c==1:
    print(a)
elif c>=2:
    print("{},{}".format(a,b),end='')
    for i in range (c):
        d=a+b
        print(",{}".format(d),end='')
        a=b
        b=d
