#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 25 16:57:42 2020

@author: jorge
"""
a= int (input("Put your grade:"))
if a<70:
    print ("You failed:(")
elif a>=70 and a<=75:
    print ("That was close")
elif a>= 76 and a<=85:
    print ("Good")
elif a>=86 and a<=95:
    print ("Incredible")
else:
    print ("OMG :0")